server:
  port: 8791
spring:
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    message-codes-resolver-format: postfix_error_code
    servlet:
      path: /dct
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: false
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://172.20.0.9:8080/auth/realms/qkdatacenter
dolphinscheduler:
  client:
    enabled: true
    defaultBaseUrl: http://dolphinscheduler.qk.cc:31352/dolphinscheduler
    tokenKey: token
    tokenValue: 278f7dd1ce2f50b514d5b709688ea34c
  task:
    code: 5172696944352
    name: shell-work
    description: 'shell work 配置'
    taskType: SHELL
    tenantCode: default
    taskParams:
      resourceList: []
      rawScript: /opt/soft/jdk11/bin/java -jar /opt/soft/dqc-hive-jdbc-exec/dam-hiveserver2-1.0.1-RELEASE.jar
      localParams: []
      dependence: {}
      conditionResult:
        successNode: []
        failedNode: []
      waitStartTimeout: {}
      switchResult: {}
    flag: 'YES'
    taskPriority: MEDIUM
    workerGroup: default
    failRetryTimes: '0'
    failRetryInterval: '1'
    timeoutFlag: CLOSE
    timeoutNotifyStrategy: ''
    timeout: 0
    delayTime: '0'
    environmentCode: 5172696944352
    projectCode: 5262418498656
atlas:
  rest:
    address: http://172.21.32.2:21000
    basicAuth: admin,admin