stages:
  - dev
variables:
  CI_DEBUG_TRACE: true
  SONAR_HOST_URL: http://172.31.0.44:9000/
sonarqube_analysis:
  stage: dev
  only:
    - dev
    - test
  script:
    - /home/zdm/sonar-scanner-4.6.2.2472/bin/sonar-scanner -Dsonar.host.url=http://172.31.0.44:9000  -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.sources=.  -Dsonar.java.binaries=. -Dsonar.analysis.CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME -Dsonar.analysis.GITLAB_USER_EMAIL=$GITLAB_USER_EMAIL -Dsonar.analysis.GITLAB_USER_NAME=$GITLAB_USER_NAME -Dsonar.analysis.CI_PROJECT_PATH=$CI_PROJECT_PATH   -Dsonar.login=admin  -Dsonar.password=admin
  tags:
    - sonarqube