server:
  port: 8780
spring:
  messages:
    basename: i18n/messages
  mvc:
    message-codes-resolver-format: postfix_error_code
    servlet:
      path: /dsd
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.20.0.9:8080/auth/realms/qkdatacenter