kind: Service
apiVersion: v1
metadata:
  name: dataservice
  namespace: java-backend
  labels:
    app: dataservice
  annotations:
    kubesphere.io/alias-name: 数据服务后端服务
    kubesphere.io/creator: admin
spec:
  ports:
    - name: http-8786
      protocol: TCP
      port: 8786
      targetPort: 8786
  selector:
    app: dataservice-deploy
    version: v1
  type: ClusterIP
  sessionAffinity: None
