kind: Deployment
apiVersion: apps/v1
metadata:
  name: dsd-deploy
  namespace: java-backend
  labels:
    app: dsd-deploy
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsd-deploy
      version: v1
  template:
    metadata:
      labels:
        app: dsd-deploy
        version: v1
    spec:
      containers:
        - name: $BUILD_NUMBER-dsd$BRANCH_NAME
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:$BRANCH_NAME-1.0.0-$BUILD_NUMBER
          ports:
            - name: tcp-8789
              containerPort: 8789
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      securityContext: {}
      imagePullSecrets:
        - name: harbor
      affinity: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600