kind: Service
apiVersion: v1
metadata:
  name: dsd
  namespace: java-backend
  labels:
    app: dsd
  annotations:
    kubesphere.io/alias-name: 数据标准后端服务
    kubesphere.io/creator: admin
spec:
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: dsd-deploy
    version: v1
  type: ClusterIP
  sessionAffinity: None
