kind: Service
apiVersion: v1
metadata:
  name: metadata
  namespace: backend-dam
  labels:
    app: metadata
  annotations:
    kubesphere.io/alias-name: 元数据后端服务
    kubesphere.io/creator: admin
spec:
  ports:
    - name: http-80
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: metadata-deploy
    version: v1
  type: ClusterIP
  sessionAffinity: None
