server:
  port: 8881
spring:
  messages:
    basename: i18n/messages
  mvc:
    message-codes-resolver-format: postfix_error_code
    servlet:
      path: /rpt
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: false