server:
  port: 8889
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  messages:
    basename: i18n/messages
  mvc:
    message-codes-resolver-format: postfix_error_code
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: false