/*
 * Dolphin Scheduler Api Docs
 * Dolphin Scheduler Api Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qk.datacenter.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.qk.datacenter.client.JSON;
/**
 * SparkDatasourceParamDTO
 */
@JsonPropertyOrder({
  SparkDatasourceParamDTO.JSON_PROPERTY_DATABASE,
  SparkDatasourceParamDTO.JSON_PROPERTY_HOST,
  SparkDatasourceParamDTO.JSON_PROPERTY_ID,
  SparkDatasourceParamDTO.JSON_PROPERTY_JAVA_SECURITY_KRB5_CONF,
  SparkDatasourceParamDTO.JSON_PROPERTY_LOGIN_USER_KEYTAB_PATH,
  SparkDatasourceParamDTO.JSON_PROPERTY_LOGIN_USER_KEYTAB_USERNAME,
  SparkDatasourceParamDTO.JSON_PROPERTY_NAME,
  SparkDatasourceParamDTO.JSON_PROPERTY_NOTE,
  SparkDatasourceParamDTO.JSON_PROPERTY_OTHER,
  SparkDatasourceParamDTO.JSON_PROPERTY_PASSWORD,
  SparkDatasourceParamDTO.JSON_PROPERTY_PORT,
  SparkDatasourceParamDTO.JSON_PROPERTY_PRINCIPAL,
  SparkDatasourceParamDTO.JSON_PROPERTY_USER_NAME
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-18T14:27:46.433909+08:00[Asia/Shanghai]")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "type", visible = true)

public class SparkDatasourceParamDTO extends BaseDataSourceParamDTO {
  public static final String JSON_PROPERTY_DATABASE = "database";
  private String database;

  public static final String JSON_PROPERTY_HOST = "host";
  private String host;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_JAVA_SECURITY_KRB5_CONF = "javaSecurityKrb5Conf";
  private String javaSecurityKrb5Conf;

  public static final String JSON_PROPERTY_LOGIN_USER_KEYTAB_PATH = "loginUserKeytabPath";
  private String loginUserKeytabPath;

  public static final String JSON_PROPERTY_LOGIN_USER_KEYTAB_USERNAME = "loginUserKeytabUsername";
  private String loginUserKeytabUsername;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_NOTE = "note";
  private String note;

  public static final String JSON_PROPERTY_OTHER = "other";
  private Map<String, String> other = null;

  public static final String JSON_PROPERTY_PASSWORD = "password";
  private String password;

  public static final String JSON_PROPERTY_PORT = "port";
  private Integer port;

  public static final String JSON_PROPERTY_PRINCIPAL = "principal";
  private String principal;

  public static final String JSON_PROPERTY_USER_NAME = "userName";
  private String userName;


  public SparkDatasourceParamDTO database(String database) {
    this.database = database;
    return this;
  }

   /**
   * Get database
   * @return database
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DATABASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDatabase() {
    return database;
  }


  @JsonProperty(JSON_PROPERTY_DATABASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatabase(String database) {
    this.database = database;
  }


  public SparkDatasourceParamDTO host(String host) {
    this.host = host;
    return this;
  }

   /**
   * Get host
   * @return host
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_HOST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHost() {
    return host;
  }


  @JsonProperty(JSON_PROPERTY_HOST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHost(String host) {
    this.host = host;
  }


  public SparkDatasourceParamDTO id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public SparkDatasourceParamDTO javaSecurityKrb5Conf(String javaSecurityKrb5Conf) {
    this.javaSecurityKrb5Conf = javaSecurityKrb5Conf;
    return this;
  }

   /**
   * Get javaSecurityKrb5Conf
   * @return javaSecurityKrb5Conf
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_JAVA_SECURITY_KRB5_CONF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJavaSecurityKrb5Conf() {
    return javaSecurityKrb5Conf;
  }


  @JsonProperty(JSON_PROPERTY_JAVA_SECURITY_KRB5_CONF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJavaSecurityKrb5Conf(String javaSecurityKrb5Conf) {
    this.javaSecurityKrb5Conf = javaSecurityKrb5Conf;
  }


  public SparkDatasourceParamDTO loginUserKeytabPath(String loginUserKeytabPath) {
    this.loginUserKeytabPath = loginUserKeytabPath;
    return this;
  }

   /**
   * Get loginUserKeytabPath
   * @return loginUserKeytabPath
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOGIN_USER_KEYTAB_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoginUserKeytabPath() {
    return loginUserKeytabPath;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_USER_KEYTAB_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoginUserKeytabPath(String loginUserKeytabPath) {
    this.loginUserKeytabPath = loginUserKeytabPath;
  }


  public SparkDatasourceParamDTO loginUserKeytabUsername(String loginUserKeytabUsername) {
    this.loginUserKeytabUsername = loginUserKeytabUsername;
    return this;
  }

   /**
   * Get loginUserKeytabUsername
   * @return loginUserKeytabUsername
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LOGIN_USER_KEYTAB_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLoginUserKeytabUsername() {
    return loginUserKeytabUsername;
  }


  @JsonProperty(JSON_PROPERTY_LOGIN_USER_KEYTAB_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoginUserKeytabUsername(String loginUserKeytabUsername) {
    this.loginUserKeytabUsername = loginUserKeytabUsername;
  }


  public SparkDatasourceParamDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public SparkDatasourceParamDTO note(String note) {
    this.note = note;
    return this;
  }

   /**
   * Get note
   * @return note
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNote() {
    return note;
  }


  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNote(String note) {
    this.note = note;
  }


  public SparkDatasourceParamDTO other(Map<String, String> other) {
    this.other = other;
    return this;
  }

  public SparkDatasourceParamDTO putOtherItem(String key, String otherItem) {
    if (this.other == null) {
      this.other = new HashMap<>();
    }
    this.other.put(key, otherItem);
    return this;
  }

   /**
   * Get other
   * @return other
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OTHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getOther() {
    return other;
  }


  @JsonProperty(JSON_PROPERTY_OTHER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOther(Map<String, String> other) {
    this.other = other;
  }


  public SparkDatasourceParamDTO password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassword() {
    return password;
  }


  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassword(String password) {
    this.password = password;
  }


  public SparkDatasourceParamDTO port(Integer port) {
    this.port = port;
    return this;
  }

   /**
   * Get port
   * @return port
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPort() {
    return port;
  }


  @JsonProperty(JSON_PROPERTY_PORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPort(Integer port) {
    this.port = port;
  }


  public SparkDatasourceParamDTO principal(String principal) {
    this.principal = principal;
    return this;
  }

   /**
   * Get principal
   * @return principal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PRINCIPAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPrincipal() {
    return principal;
  }


  @JsonProperty(JSON_PROPERTY_PRINCIPAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrincipal(String principal) {
    this.principal = principal;
  }


  public SparkDatasourceParamDTO userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_USER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserName() {
    return userName;
  }


  @JsonProperty(JSON_PROPERTY_USER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserName(String userName) {
    this.userName = userName;
  }


  /**
   * Return true if this SparkDatasourceParamDTO object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SparkDatasourceParamDTO sparkDatasourceParamDTO = (SparkDatasourceParamDTO) o;
    return Objects.equals(this.database, sparkDatasourceParamDTO.database) &&
        Objects.equals(this.host, sparkDatasourceParamDTO.host) &&
        Objects.equals(this.id, sparkDatasourceParamDTO.id) &&
        Objects.equals(this.javaSecurityKrb5Conf, sparkDatasourceParamDTO.javaSecurityKrb5Conf) &&
        Objects.equals(this.loginUserKeytabPath, sparkDatasourceParamDTO.loginUserKeytabPath) &&
        Objects.equals(this.loginUserKeytabUsername, sparkDatasourceParamDTO.loginUserKeytabUsername) &&
        Objects.equals(this.name, sparkDatasourceParamDTO.name) &&
        Objects.equals(this.note, sparkDatasourceParamDTO.note) &&
        Objects.equals(this.other, sparkDatasourceParamDTO.other) &&
        Objects.equals(this.password, sparkDatasourceParamDTO.password) &&
        Objects.equals(this.port, sparkDatasourceParamDTO.port) &&
        Objects.equals(this.principal, sparkDatasourceParamDTO.principal) &&
        Objects.equals(this.userName, sparkDatasourceParamDTO.userName) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(database, host, id, javaSecurityKrb5Conf, loginUserKeytabPath, loginUserKeytabUsername, name, note, other, password, port, principal, userName, super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SparkDatasourceParamDTO {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    database: ").append(toIndentedString(database)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    javaSecurityKrb5Conf: ").append(toIndentedString(javaSecurityKrb5Conf)).append("\n");
    sb.append("    loginUserKeytabPath: ").append(toIndentedString(loginUserKeytabPath)).append("\n");
    sb.append("    loginUserKeytabUsername: ").append(toIndentedString(loginUserKeytabUsername)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    other: ").append(toIndentedString(other)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    principal: ").append(toIndentedString(principal)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

static {
  // Initialize and register the discriminator mappings.
  Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
  mappings.put("SparkDatasourceParamDTO", SparkDatasourceParamDTO.class);
  JSON.registerDiscriminator(SparkDatasourceParamDTO.class, "type", mappings);
}
}

