/*
 * Dolphin Scheduler Api Docs
 * Dolphin Scheduler Api Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qk.datacenter.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.qk.datacenter.model.ProcessDefinition;
import com.qk.datacenter.model.ProcessTaskRelation;
import com.qk.datacenter.model.TaskDefinition;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * DagData
 */
@JsonPropertyOrder({
  DagData.JSON_PROPERTY_PROCESS_DEFINITION,
  DagData.JSON_PROPERTY_PROCESS_TASK_RELATION_LIST,
  DagData.JSON_PROPERTY_TASK_DEFINITION_LIST
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-18T14:27:46.433909+08:00[Asia/Shanghai]")
public class DagData {
  public static final String JSON_PROPERTY_PROCESS_DEFINITION = "processDefinition";
  private ProcessDefinition processDefinition;

  public static final String JSON_PROPERTY_PROCESS_TASK_RELATION_LIST = "processTaskRelationList";
  private List<ProcessTaskRelation> processTaskRelationList = null;

  public static final String JSON_PROPERTY_TASK_DEFINITION_LIST = "taskDefinitionList";
  private List<TaskDefinition> taskDefinitionList = null;


  public DagData processDefinition(ProcessDefinition processDefinition) {
    this.processDefinition = processDefinition;
    return this;
  }

   /**
   * Get processDefinition
   * @return processDefinition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProcessDefinition getProcessDefinition() {
    return processDefinition;
  }


  @JsonProperty(JSON_PROPERTY_PROCESS_DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessDefinition(ProcessDefinition processDefinition) {
    this.processDefinition = processDefinition;
  }


  public DagData processTaskRelationList(List<ProcessTaskRelation> processTaskRelationList) {
    this.processTaskRelationList = processTaskRelationList;
    return this;
  }

  public DagData addProcessTaskRelationListItem(ProcessTaskRelation processTaskRelationListItem) {
    if (this.processTaskRelationList == null) {
      this.processTaskRelationList = new ArrayList<>();
    }
    this.processTaskRelationList.add(processTaskRelationListItem);
    return this;
  }

   /**
   * Get processTaskRelationList
   * @return processTaskRelationList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PROCESS_TASK_RELATION_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ProcessTaskRelation> getProcessTaskRelationList() {
    return processTaskRelationList;
  }


  @JsonProperty(JSON_PROPERTY_PROCESS_TASK_RELATION_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessTaskRelationList(List<ProcessTaskRelation> processTaskRelationList) {
    this.processTaskRelationList = processTaskRelationList;
  }


  public DagData taskDefinitionList(List<TaskDefinition> taskDefinitionList) {
    this.taskDefinitionList = taskDefinitionList;
    return this;
  }

  public DagData addTaskDefinitionListItem(TaskDefinition taskDefinitionListItem) {
    if (this.taskDefinitionList == null) {
      this.taskDefinitionList = new ArrayList<>();
    }
    this.taskDefinitionList.add(taskDefinitionListItem);
    return this;
  }

   /**
   * Get taskDefinitionList
   * @return taskDefinitionList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TASK_DEFINITION_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TaskDefinition> getTaskDefinitionList() {
    return taskDefinitionList;
  }


  @JsonProperty(JSON_PROPERTY_TASK_DEFINITION_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaskDefinitionList(List<TaskDefinition> taskDefinitionList) {
    this.taskDefinitionList = taskDefinitionList;
  }


  /**
   * Return true if this DagData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DagData dagData = (DagData) o;
    return Objects.equals(this.processDefinition, dagData.processDefinition) &&
        Objects.equals(this.processTaskRelationList, dagData.processTaskRelationList) &&
        Objects.equals(this.taskDefinitionList, dagData.taskDefinitionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processDefinition, processTaskRelationList, taskDefinitionList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DagData {\n");
    sb.append("    processDefinition: ").append(toIndentedString(processDefinition)).append("\n");
    sb.append("    processTaskRelationList: ").append(toIndentedString(processTaskRelationList)).append("\n");
    sb.append("    taskDefinitionList: ").append(toIndentedString(taskDefinitionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

