/*
 * Dolphin Scheduler Api Docs
 * Dolphin Scheduler Api Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.qk.datacenter.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * WorkFlowLineage
 */
@JsonPropertyOrder({
  WorkFlowLineage.JSON_PROPERTY_CRONTAB,
  WorkFlowLineage.JSON_PROPERTY_SCHEDULE_END_TIME,
  WorkFlowLineage.JSON_PROPERTY_SCHEDULE_PUBLISH_STATUS,
  WorkFlowLineage.JSON_PROPERTY_SCHEDULE_START_TIME,
  WorkFlowLineage.JSON_PROPERTY_SOURCE_WORK_FLOW_CODE,
  WorkFlowLineage.JSON_PROPERTY_WORK_FLOW_CODE,
  WorkFlowLineage.JSON_PROPERTY_WORK_FLOW_NAME,
  WorkFlowLineage.JSON_PROPERTY_WORK_FLOW_PUBLISH_STATUS
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-18T14:27:46.433909+08:00[Asia/Shanghai]")
public class WorkFlowLineage {
  public static final String JSON_PROPERTY_CRONTAB = "crontab";
  private String crontab;

  public static final String JSON_PROPERTY_SCHEDULE_END_TIME = "scheduleEndTime";
  private OffsetDateTime scheduleEndTime;

  public static final String JSON_PROPERTY_SCHEDULE_PUBLISH_STATUS = "schedulePublishStatus";
  private Integer schedulePublishStatus;

  public static final String JSON_PROPERTY_SCHEDULE_START_TIME = "scheduleStartTime";
  private OffsetDateTime scheduleStartTime;

  public static final String JSON_PROPERTY_SOURCE_WORK_FLOW_CODE = "sourceWorkFlowCode";
  private String sourceWorkFlowCode;

  public static final String JSON_PROPERTY_WORK_FLOW_CODE = "workFlowCode";
  private Long workFlowCode;

  public static final String JSON_PROPERTY_WORK_FLOW_NAME = "workFlowName";
  private String workFlowName;

  public static final String JSON_PROPERTY_WORK_FLOW_PUBLISH_STATUS = "workFlowPublishStatus";
  private String workFlowPublishStatus;


  public WorkFlowLineage crontab(String crontab) {
    this.crontab = crontab;
    return this;
  }

   /**
   * Get crontab
   * @return crontab
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CRONTAB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCrontab() {
    return crontab;
  }


  @JsonProperty(JSON_PROPERTY_CRONTAB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCrontab(String crontab) {
    this.crontab = crontab;
  }


  public WorkFlowLineage scheduleEndTime(OffsetDateTime scheduleEndTime) {
    this.scheduleEndTime = scheduleEndTime;
    return this;
  }

   /**
   * Get scheduleEndTime
   * @return scheduleEndTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCHEDULE_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getScheduleEndTime() {
    return scheduleEndTime;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULE_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduleEndTime(OffsetDateTime scheduleEndTime) {
    this.scheduleEndTime = scheduleEndTime;
  }


  public WorkFlowLineage schedulePublishStatus(Integer schedulePublishStatus) {
    this.schedulePublishStatus = schedulePublishStatus;
    return this;
  }

   /**
   * Get schedulePublishStatus
   * @return schedulePublishStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCHEDULE_PUBLISH_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSchedulePublishStatus() {
    return schedulePublishStatus;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULE_PUBLISH_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSchedulePublishStatus(Integer schedulePublishStatus) {
    this.schedulePublishStatus = schedulePublishStatus;
  }


  public WorkFlowLineage scheduleStartTime(OffsetDateTime scheduleStartTime) {
    this.scheduleStartTime = scheduleStartTime;
    return this;
  }

   /**
   * Get scheduleStartTime
   * @return scheduleStartTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SCHEDULE_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getScheduleStartTime() {
    return scheduleStartTime;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULE_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduleStartTime(OffsetDateTime scheduleStartTime) {
    this.scheduleStartTime = scheduleStartTime;
  }


  public WorkFlowLineage sourceWorkFlowCode(String sourceWorkFlowCode) {
    this.sourceWorkFlowCode = sourceWorkFlowCode;
    return this;
  }

   /**
   * Get sourceWorkFlowCode
   * @return sourceWorkFlowCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SOURCE_WORK_FLOW_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceWorkFlowCode() {
    return sourceWorkFlowCode;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_WORK_FLOW_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceWorkFlowCode(String sourceWorkFlowCode) {
    this.sourceWorkFlowCode = sourceWorkFlowCode;
  }


  public WorkFlowLineage workFlowCode(Long workFlowCode) {
    this.workFlowCode = workFlowCode;
    return this;
  }

   /**
   * Get workFlowCode
   * @return workFlowCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WORK_FLOW_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getWorkFlowCode() {
    return workFlowCode;
  }


  @JsonProperty(JSON_PROPERTY_WORK_FLOW_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWorkFlowCode(Long workFlowCode) {
    this.workFlowCode = workFlowCode;
  }


  public WorkFlowLineage workFlowName(String workFlowName) {
    this.workFlowName = workFlowName;
    return this;
  }

   /**
   * Get workFlowName
   * @return workFlowName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WORK_FLOW_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWorkFlowName() {
    return workFlowName;
  }


  @JsonProperty(JSON_PROPERTY_WORK_FLOW_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWorkFlowName(String workFlowName) {
    this.workFlowName = workFlowName;
  }


  public WorkFlowLineage workFlowPublishStatus(String workFlowPublishStatus) {
    this.workFlowPublishStatus = workFlowPublishStatus;
    return this;
  }

   /**
   * Get workFlowPublishStatus
   * @return workFlowPublishStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WORK_FLOW_PUBLISH_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWorkFlowPublishStatus() {
    return workFlowPublishStatus;
  }


  @JsonProperty(JSON_PROPERTY_WORK_FLOW_PUBLISH_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWorkFlowPublishStatus(String workFlowPublishStatus) {
    this.workFlowPublishStatus = workFlowPublishStatus;
  }


  /**
   * Return true if this WorkFlowLineage object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkFlowLineage workFlowLineage = (WorkFlowLineage) o;
    return Objects.equals(this.crontab, workFlowLineage.crontab) &&
        Objects.equals(this.scheduleEndTime, workFlowLineage.scheduleEndTime) &&
        Objects.equals(this.schedulePublishStatus, workFlowLineage.schedulePublishStatus) &&
        Objects.equals(this.scheduleStartTime, workFlowLineage.scheduleStartTime) &&
        Objects.equals(this.sourceWorkFlowCode, workFlowLineage.sourceWorkFlowCode) &&
        Objects.equals(this.workFlowCode, workFlowLineage.workFlowCode) &&
        Objects.equals(this.workFlowName, workFlowLineage.workFlowName) &&
        Objects.equals(this.workFlowPublishStatus, workFlowLineage.workFlowPublishStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(crontab, scheduleEndTime, schedulePublishStatus, scheduleStartTime, sourceWorkFlowCode, workFlowCode, workFlowName, workFlowPublishStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkFlowLineage {\n");
    sb.append("    crontab: ").append(toIndentedString(crontab)).append("\n");
    sb.append("    scheduleEndTime: ").append(toIndentedString(scheduleEndTime)).append("\n");
    sb.append("    schedulePublishStatus: ").append(toIndentedString(schedulePublishStatus)).append("\n");
    sb.append("    scheduleStartTime: ").append(toIndentedString(scheduleStartTime)).append("\n");
    sb.append("    sourceWorkFlowCode: ").append(toIndentedString(sourceWorkFlowCode)).append("\n");
    sb.append("    workFlowCode: ").append(toIndentedString(workFlowCode)).append("\n");
    sb.append("    workFlowName: ").append(toIndentedString(workFlowName)).append("\n");
    sb.append("    workFlowPublishStatus: ").append(toIndentedString(workFlowPublishStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

